name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install protobuf-c-compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-c-compiler

      - name: Run CMake
        run: |
            cmake -S . -B build
            cmake --build build -j 2

      # - name: Run tests
      #   run: |
      #     cd build
      #     ctest --output-on-failure

